package com.fairyringmap;

import java.awt.Color;
import java.awt.image.BufferedImage;
import java.io.InputStream;
import javax.imageio.ImageIO;
import static org.junit.Assert.assertEquals;
import static org.junit.Assert.assertNotNull;
import static org.junit.Assert.assertTrue;
import org.junit.Test;

/**
 * Pins the runtime recolour against the shipped sprites.
 * <p>
 * The shipped PNGs were generated by {@code cache-tools/tools/recolour-sprite.py}, and
 * {@link SpriteRecolour} is a port of that script so markers can be recoloured from config at
 * runtime. Two implementations of one formula drift, and the drift would be invisible: a slightly
 * wrong ramp still looks like a ring. So the test does not check properties of the output, it
 * checks that recolouring the base sprite reproduces the shipped one **exactly**.
 */
public class SpriteRecolourTest
{
	private BufferedImage load(String name) throws Exception
	{
		try (InputStream in = getClass().getResourceAsStream("/FairyRingMap/" + name))
		{
			assertNotNull(name + " is not on the classpath", in);
			return ImageIO.read(in);
		}
	}

	private void assertSame(BufferedImage expected, BufferedImage actual, String what)
	{
		assertEquals(what + ": width", expected.getWidth(), actual.getWidth());
		assertEquals(what + ": height", expected.getHeight(), actual.getHeight());
		for (int y = 0; y < expected.getHeight(); y++)
		{
			for (int x = 0; x < expected.getWidth(); x++)
			{
				int a = expected.getRGB(x, y);
				int b = actual.getRGB(x, y);
				// Fully transparent pixels may differ in their unused colour channels.
				if ((a >>> 24) == 0 && (b >>> 24) == 0)
				{
					continue;
				}
				assertEquals(String.format("%s: pixel %d,%d expected %08X got %08X", what, x, y, a, b),
					a, b);
			}
		}
	}

	/**
	 * The load-bearing one. {@code ring-fave.png} was produced by the Python script from
	 * {@code ring.png} and {@code #E92100}; doing the same here must give the same bytes.
	 */
	@Test
	public void matchesTheShippedFavouriteSprite() throws Exception
	{
		BufferedImage recoloured = SpriteRecolour.recolour(load("ring.png"), new Color(0xE92100));
		assertSame(load("ring-fave.png"), recoloured, "ring-fave");
	}

	/** Same again for the selected marker, which came from the same base and the same script. */
	@Test
	public void matchesTheShippedSelectedSprite() throws Exception
	{
		BufferedImage recoloured = SpriteRecolour.recolour(load("ring.png"), new Color(0xFF981F));
		assertSame(load("ring-selected.png"), recoloured, "ring-selected");
	}

	/**
	 * Recolouring is idempotent: the output is already on the ramp, so doing it again changes
	 * nothing. This is the property that matters at runtime, where a config change can recolour a
	 * sprite that has already been recoloured.
	 * <p>
	 * Note it is <em>not</em> true that recolouring {@code ring.png} to its own {@code #3FD9C8}
	 * returns {@code ring.png}. That sprite is the hand-drawn original and the other four were
	 * generated from it, so its soft edge pixels sit slightly off the ramp — pixel 0,0 is
	 * {@code 004040} at alpha 4 where the ramp gives {@code 13403B}. The difference is confined to
	 * nearly-transparent pixels and is invisible, but it is why {@link FairyRingMap} leaves the
	 * shipped sprite in place when the configured colour is the default.
	 */
	@Test
	public void recolouringIsIdempotent() throws Exception
	{
		Color target = new Color(0xE92100);
		BufferedImage once = SpriteRecolour.recolour(load("ring.png"), target);
		BufferedImage twice = SpriteRecolour.recolour(once, target);
		assertSame(once, twice, "recoloured twice");
	}

	/**
	 * An opaque target leaves alpha alone. Alpha is the marker's shape — a soft edge is what stops
	 * an eleven-pixel circle looking like a square — so a plain recolour must not touch it.
	 */
	@Test
	public void alphaIsPreserved() throws Exception
	{
		BufferedImage ring = load("ring.png");
		BufferedImage out = SpriteRecolour.recolour(ring, new Color(0x123456));
		for (int y = 0; y < ring.getHeight(); y++)
		{
			for (int x = 0; x < ring.getWidth(); x++)
			{
				assertEquals("alpha at " + x + "," + y,
					ring.getRGB(x, y) >>> 24, out.getRGB(x, y) >>> 24);
			}
		}
	}

	/**
	 * A translucent target changes nothing, because it cannot. The client's sprite format has no
	 * alpha channel, so marker transparency is widget opacity rather than pixels - pinning that
	 * here stops someone "fixing" this method to honour alpha and believing it worked.
	 */
	@Test
	public void aTranslucentTargetIsIgnoredBecauseSpritesHaveNoAlpha() throws Exception
	{
		BufferedImage ring = load("ring.png");
		BufferedImage opaque = SpriteRecolour.recolour(ring, new Color(0x12, 0x34, 0x56, 255));
		BufferedImage faded = SpriteRecolour.recolour(ring, new Color(0x12, 0x34, 0x56, 40));
		assertSame(opaque, faded, "alpha should not change the pixels");
	}

	/** The brightest pixel becomes the requested colour exactly; that is what "recolour" means. */
	@Test
	public void theBrightestPixelBecomesTheTargetColour() throws Exception
	{
		BufferedImage out = SpriteRecolour.recolour(load("ring.png"), new Color(0x8040C0));
		int brightest = 0;
		int best = -1;
		for (int y = 0; y < out.getHeight(); y++)
		{
			for (int x = 0; x < out.getWidth(); x++)
			{
				int argb = out.getRGB(x, y);
				if ((argb >>> 24) <= 128)
				{
					continue;
				}
				int sum = ((argb >> 16) & 0xFF) + ((argb >> 8) & 0xFF) + (argb & 0xFF);
				if (sum > best)
				{
					best = sum;
					brightest = argb & 0xFFFFFF;
				}
			}
		}
		assertTrue("expected some opaque pixels", best > 0);
		assertEquals(0x8040C0, brightest);
	}
}
